CREATE TABLE public."Product" (
	"Id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Description" varchar(255) NULL,
	"Price" numeric NULL,
	"ProviderId" int NOT NULL,
	CONSTRAINT product_pk PRIMARY KEY ("Id")
);


CREATE TABLE public."Tag" (
	"Id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Name" varchar(255) NULL,
	"ProductId" int NOT NULL,
	CONSTRAINT tag_pk PRIMARY KEY ("Id")
);

CREATE TABLE public."Provider" (
	"Id" int NOT NULL,
	"SocialName" varchar NULL,
	"FantasyName" varchar(255) NULL,
	CONSTRAINT provider_pk PRIMARY KEY ("Id")
);


ALTER TABLE public."Tag" ADD CONSTRAINT tag_fk FOREIGN KEY ("ProductId") REFERENCES public."Product"("Id");
ALTER TABLE public."Product" ADD CONSTRAINT product_fk FOREIGN KEY ("ProviderId") REFERENCES public."Provider"("Id");
