insert into public."Product" ("Description", "Price") values ('Mushroom - Shitake, Dry', 57);
insert into public."Product" ("Description", "Price") values ('Muffin Mix - Oatmeal', 89);
insert into public."Product" ("Description", "Price") values ('Glaze - Clear', 40);
insert into public."Product" ("Description", "Price") values ('Cabbage - Nappa', 5);
insert into public."Product" ("Description", "Price") values ('Creme De Menth - White', 51);
insert into public."Product" ("Description", "Price") values ('Jolt Cola', 26);
insert into public."Product" ("Description", "Price") values ('Sage - Ground', 95);
insert into public."Product" ("Description", "Price") values ('Juice - Orangina', 26);
insert into public."Product" ("Description", "Price") values ('Beans - Kidney, Canned', 30);
insert into public."Product" ("Description", "Price") values ('Doilies - 12, Paper', 39);
insert into public."Product" ("Description", "Price") values ('Corn - Mini', 13);
insert into public."Product" ("Description", "Price") values ('Tart Shells - Sweet, 2', 95);
insert into public."Product" ("Description", "Price") values ('Calvados - Boulard', 81);
insert into public."Product" ("Description", "Price") values ('Bread - White, Sliced', 88);
insert into public."Product" ("Description", "Price") values ('Tea - Apple Green Tea', 5);
insert into public."Product" ("Description", "Price") values ('Lettuce - Belgian Endive', 93);
insert into public."Product" ("Description", "Price") values ('Spinach - Baby', 93);
insert into public."Product" ("Description", "Price") values ('Wine - Carmenere Casillero Del', 40);
insert into public."Product" ("Description", "Price") values ('Appetizer - Shrimp Puff', 38);
insert into public."Product" ("Description", "Price") values ('Pork - Ham, Virginia', 16);
insert into public."Product" ("Description", "Price") values ('Danishes - Mini Raspberry', 53);
insert into public."Product" ("Description", "Price") values ('Tumeric', 29);
insert into public."Product" ("Description", "Price") values ('Salmon - Atlantic, No Skin', 61);
insert into public."Product" ("Description", "Price") values ('Ginsing - Fresh', 75);
insert into public."Product" ("Description", "Price") values ('Cup - 6oz, Foam', 12);
insert into public."Product" ("Description", "Price") values ('Table Cloth 81x81 Colour', 56);
insert into public."Product" ("Description", "Price") values ('Clams - Canned', 76);
insert into public."Product" ("Description", "Price") values ('Gin - Gilbeys London, Dry', 85);
insert into public."Product" ("Description", "Price") values ('Wine - Placido Pinot Grigo', 58);
insert into public."Product" ("Description", "Price") values ('Pur Value', 96);
insert into public."Product" ("Description", "Price") values ('Mountain Dew', 61);
insert into public."Product" ("Description", "Price") values ('Soup - Base Broth Chix', 88);
insert into public."Product" ("Description", "Price") values ('Wine - Beaujolais Villages', 73);
insert into public."Product" ("Description", "Price") values ('Wine - Chardonnay South', 75);
insert into public."Product" ("Description", "Price") values ('Muffin Batt - Blueberry Passion', 66);
insert into public."Product" ("Description", "Price") values ('Onions - Vidalia', 33);
insert into public."Product" ("Description", "Price") values ('Fuji Apples', 15);
insert into public."Product" ("Description", "Price") values ('Lamb - Leg, Diced', 77);
insert into public."Product" ("Description", "Price") values ('Pails With Lids', 86);
insert into public."Product" ("Description", "Price") values ('Pumpkin', 83);
insert into public."Product" ("Description", "Price") values ('Tray - Foam, Square 4 - S', 90);
insert into public."Product" ("Description", "Price") values ('Gatorade - Fruit Punch', 47);
insert into public."Product" ("Description", "Price") values ('Tomato - Tricolor Cherry', 40);
insert into public."Product" ("Description", "Price") values ('Longos - Cheese Tortellini', 24);
insert into public."Product" ("Description", "Price") values ('Grapes - Red', 22);
insert into public."Product" ("Description", "Price") values ('Sauce - Bernaise, Mix', 99);
insert into public."Product" ("Description", "Price") values ('Durian Fruit', 17);
insert into public."Product" ("Description", "Price") values ('Sansho Powder', 96);
insert into public."Product" ("Description", "Price") values ('Carbonated Water - Wildberry', 49);
insert into public."Product" ("Description", "Price") values ('Nantucket - 518ml', 53);
insert into public."Product" ("Description", "Price") values ('Grenadillo', 95);
insert into public."Product" ("Description", "Price") values ('Juice - Orange 1.89l', 15);
insert into public."Product" ("Description", "Price") values ('Wine - Two Oceans Sauvignon', 82);
insert into public."Product" ("Description", "Price") values ('Food Colouring - Blue', 28);
insert into public."Product" ("Description", "Price") values ('Soupcontfoam16oz 116con', 54);
insert into public."Product" ("Description", "Price") values ('Wine - Niagara,vqa Reisling', 83);
insert into public."Product" ("Description", "Price") values ('Venison - Racks Frenched', 91);
insert into public."Product" ("Description", "Price") values ('Ham - Virginia', 40);
insert into public."Product" ("Description", "Price") values ('Cabbage - Green', 18);
insert into public."Product" ("Description", "Price") values ('Lamb - Leg, Diced', 46);
insert into public."Product" ("Description", "Price") values ('Peas - Pigeon, Dry', 38);
insert into public."Product" ("Description", "Price") values ('Bread Foccacia Whole', 42);
insert into public."Product" ("Description", "Price") values ('Glass - Wine, Plastic, Clear 5 Oz', 29);
insert into public."Product" ("Description", "Price") values ('Pepper - Chipotle, Canned', 39);
insert into public."Product" ("Description", "Price") values ('Oxtail - Cut', 66);
insert into public."Product" ("Description", "Price") values ('Tomatoes - Hot House', 29);
insert into public."Product" ("Description", "Price") values ('Zucchini - Yellow', 56);
insert into public."Product" ("Description", "Price") values ('Oranges - Navel, 72', 26);
insert into public."Product" ("Description", "Price") values ('Energy Drink - Franks Pineapple', 20);
insert into public."Product" ("Description", "Price") values ('Veal - Liver', 60);
insert into public."Product" ("Description", "Price") values ('Cheese - Brick With Onion', 70);
insert into public."Product" ("Description", "Price") values ('Muffin - Banana Nut Individual', 96);
insert into public."Product" ("Description", "Price") values ('Sobe - Orange Carrot', 95);
insert into public."Product" ("Description", "Price") values ('Lidsoupcont Rp12dn', 60);
insert into public."Product" ("Description", "Price") values ('Durian Fruit', 62);
insert into public."Product" ("Description", "Price") values ('Chocolate - Milk', 41);
insert into public."Product" ("Description", "Price") values ('Veal - Slab Bacon', 84);
insert into public."Product" ("Description", "Price") values ('Veal - Insides Provini', 36);
insert into public."Product" ("Description", "Price") values ('Eggplant Oriental', 93);
insert into public."Product" ("Description", "Price") values ('Scallops - U - 10', 55);
insert into public."Product" ("Description", "Price") values ('Sauce - Sesame Thai Dressing', 91);
insert into public."Product" ("Description", "Price") values ('Lamb - Racks, Frenched', 85);
insert into public."Product" ("Description", "Price") values ('Doilies - 12, Paper', 33);
insert into public."Product" ("Description", "Price") values ('Salmon - Atlantic, No Skin', 94);
insert into public."Product" ("Description", "Price") values ('Vinegar - Cider', 88);
insert into public."Product" ("Description", "Price") values ('Lettuce - Boston Bib - Organic', 51);
insert into public."Product" ("Description", "Price") values ('Pork - Smoked Back Bacon', 75);
insert into public."Product" ("Description", "Price") values ('Wine - Piper Heidsieck Brut', 57);
insert into public."Product" ("Description", "Price") values ('Sprouts - Brussel', 45);
insert into public."Product" ("Description", "Price") values ('Nut - Almond, Blanched, Ground', 96);
insert into public."Product" ("Description", "Price") values ('Ice Cream Bar - Drumstick', 45);
insert into public."Product" ("Description", "Price") values ('Banana - Green', 80);
insert into public."Product" ("Description", "Price") values ('Sausage - Meat', 83);
insert into public."Product" ("Description", "Price") values ('Steampan Lid', 50);
insert into public."Product" ("Description", "Price") values ('Octopus', 17);
insert into public."Product" ("Description", "Price") values ('Pasta - Agnolotti - Butternut', 14);
insert into public."Product" ("Description", "Price") values ('Glycerine', 54);
insert into public."Product" ("Description", "Price") values ('Sour Puss Raspberry', 86);
insert into public."Product" ("Description", "Price") values ('Cheese - Brie,danish', 51);
insert into public."Product" ("Description", "Price") values ('Tuna - Sushi Grade', 26);
